dist: trusty
sudo: required
language: php
php:
  - '5.6'
  - '7.0'
  - '7.1'

branches:
  only:
    - master
    - jelix-1.7.x
    - travis

addons:
    hosts:
        - testapp17.local

cache:
    directories:
    - $HOME/.composer/cache

matrix:
    fast_finish: true

services:
   - memcached
   - redis-server
   - mysql
   - postgresql

before_install:
   - phpenv config-add testapp/travis/phpconf.ini
   - phpenv config-rm xdebug.ini
   - sudo ./testapp/travis/before_install.sh $(phpenv version-name)
   - ~/.phpenv/versions/$(phpenv version-name)/bin/composer self-update

install:
   - ./testapp/travis/install.sh

before_script:
   - ./testapp/travis/before_script.sh

script:
   - ./testapp/travis/script.sh

#after_success:
    
#after_failure:

#before_deploy:

#deploy:
#    skip_cleanup: true


#after_deploy:
    
#after_script:
