dist: bionic
os: linux
language: php
php:
  - '5.6'
  - '7.0'
  - '7.1'
  - '7.2'
  - '7.3'
  - '7.4'

branches:
  only:
    - master
    - jelix-1.8.x
    - jelix-1.7.x
    - travis

addons:
    hosts:
        - testapp.local

cache:
    directories:
    - $HOME/.composer/cache

jobs:
    fast_finish: true

services:
   - memcached
   - redis
   - mysql
   - postgresql

before_install:
   - phpenv config-add testapp/travis/phpconf.ini
   - phpenv config-rm xdebug.ini
   - sudo ./testapp/travis/before_install.sh $(phpenv version-name)
   - ~/.phpenv/versions/$(phpenv version-name)/bin/composer self-update --2

install:
   - ./testapp/travis/install.sh

before_script:
   - ./testapp/travis/before_script.sh

script:
   - ./testapp/travis/script.sh

