<?php
/**
 * @author     Laurent Jouanneau
 * @copyright  2005-2014 Laurent Jouanneau
 *
 * @see       http://www.jelix.org
 * @licence    GNU Lesser General Public Licence see LICENCE file or http://www.gnu.org/licenses/lgpl.html
 */

namespace Jelix\Core\Includer;

/**
 * interface for Includer compiler which needs only one source file.
 * The PHP file generated by the compiler should check itself
 * if it is still valid. The file should have a "return" statement
 * with a boolean : true if it is ok, false if it should be recompiled.
 */
interface SimpleCompilerInterface
{
    /**
     * parse the given file, and store the result in a cache file.
     *
     * @param \Jelix\Core\Selector\SelectorInterface $aSelector the file selector
     *
     * @return bool true : process ok
     */
    public function compile($aSelector);
}
