
#ifnot STANDALONE_CHECKER
       'checker.title'=>'Vérification de l\'installation de Jelix',
#else
#expand      'checker.title'=>'Vérification de votre serveur pour Jelix __LIB_VERSION__',
#endif
        'number.errors'         =>' erreurs.',
        'number.error'          =>' erreur.',
        'number.warnings'       =>' avertissements.',
        'number.warning'        =>' avertissement.',
        'number.notices'        =>' remarques.',
        'number.notice'         =>' remarque.',
#ifnot STANDALONE_CHECKER
        'build.not.found'       =>'Le fichier BUILD de jelix est introuvable',
        'conclusion.error'      =>'Vous devez corriger l\'erreur pour faire fonctionner correctement votre application.',
        'conclusion.errors'     =>'Vous devez corriger les erreurs pour faire fonctionner correctement votre application.',
        'conclusion.warning'    =>'Votre application peut à priori fonctionner, mais il est préférable de corriger l\'avertissement pour être sûr.',
        'conclusion.warnings'   =>'Votre application peut à priori fonctionner, mais il est préférable de corriger les avertissements pour être sûr.',
        'conclusion.notice'     =>'L\'installation est correcte malgré la remarque.',
        'conclusion.notices'    =>'L\'installation est correcte malgré les remarques.',
        'conclusion.ok'         =>'L\'installation est correcte',
#else
#expand     'conclusion.error'      =>'Vous devez corriger l\'erreur pour faire fonctionner correctement une application Jelix __LIB_VERSION__.',
#expand     'conclusion.errors'     =>'Vous devez corriger les erreurs pour faire fonctionner correctement une application Jelix __LIB_VERSION__.',
#expand     'conclusion.warning'    =>'Une application Jelix __LIB_VERSION__ peut à priori fonctionner, mais il est préférable de corriger l\'avertissement pour être sûr.',
#expand     'conclusion.warnings'   =>'Une application Jelix __LIB_VERSION__ peut à priori fonctionner, mais il est préférable de corriger les avertissements pour être sûr.',
#expand     'conclusion.notice'     =>'Aucun problème pour installer une application pour Jelix  __LIB_VERSION__ malgré la remarque.',
#expand     'conclusion.notices'    =>'Aucun problème pour installer une application pour Jelix  __LIB_VERSION__ malgré les remarques.',
#expand     'conclusion.ok'         =>'Vous pouvez installer une application avec Jelix __LIB_VERSION__',
#endif
        'cannot.continue'       =>'Les vérifications ne peuvent continuer : ',
        'extension.dom'         =>'L\'extension DOM n\'est pas installée',
        'extension.spl'         =>'L\'extension spl  n\'est pas installée',
        'extension.simplexml'   =>'L\'extension simplexml n\'est pas installée',
        'extension.pcre'        =>'L\'extension pcre n\'est pas installée',
        'extension.session'     =>'L\'extension session n\'est pas installée',
        'extension.tokenizer'   =>'L\'extension tokenizer n\'est pas installée',
        'extension.iconv'       =>'L\'extension iconv n\'est pas installée',
        'extensions.required.ok'=>'Toutes les extensions obligatoires sont installées',
        'extension.filter'      =>'Cette édition de Jelix a besoin de l\'extension filter',
        'extension.json'        =>'Cette édition de Jelix a besoin de l\'extension json',
        'extension.xmlrpc'      =>'Cette édition de Jelix a besoin de l\'extension xmlrpc',
        'extension.jelix'       =>'Cette édition de Jelix a besoin de l\'extension jelix',
        'extension.opcode.cache'=>'Cette édition de Jelix a besoin d\'une extension de cache d\'opcode (apc, eaccelerator...)',
        'path.core'             =>'Le fichier init.php  de jelix ou le fichier application.ini.php de votre application n\'est pas chargé',
        'path.temp'             =>'Le repertoire temporaire n\'est pas accessible en écriture ou alors JELIX_APP_TEMP_PATH n\'est pas configurée comme il faut',
        'path.log'              =>'Le repertoire var/log dans votre application n\'est pas accessible en écriture ou alors JELIX_APP_LOG_PATH n\'est pas configurée comme il faut',
        'path.var'              =>'JELIX_APP_VAR_PATH n\'est pas configuré correctement : ce répertoire n\'existe pas',
        'path.config'           =>'JELIX_APP_CONFIG_PATH n\'est pas configuré correctement : ce répertoire n\'existe pas',
        'path.www'              =>'JELIX_APP_WWW_PATH n\'est pas configuré correctement : ce répertoire n\'existe pas',
        'php.bad.version'       =>'Mauvaise version de PHP',
        'php.version.current'   =>'Version courante :',
        'php.version.required'  =>'Cette édition de Jelix nécessite au moins PHP ',
        'too.critical.error'    =>'Trop d\'erreurs critiques sont apparues. Corrigez les.',
        'config.file'           =>'La variable $config_file n\'existe pas ou le fichier qu\'elle indique n\'existe pas',
        'paths.ok'              =>'Les répertoires temp, log, var, config et www sont ok',
        'ini.magic_quotes_gpc_with_plugin'=>'php.ini : le plugin magicquotes est activé mais vous devriez mettre magic_quotes_gpc à off',
        'ini.magicquotes_plugin_without_php'=>'php.ini : le plugin magicquotes est activé alors que magic_quotes_gpc est déjà à off, désactivez le plugin',
        'ini.magic_quotes_gpc'  =>'php.ini : l\'activation des magicquotes n\'est pas recommandée pour jelix. Vous devez les désactiver ou activer le plugin magicquotes si ce n\'est pas fait',
        'ini.magic_quotes_runtime'=>'php.ini : magic_quotes_runtime doit être à off',
        'ini.session.auto_start'=>'php.ini : session.auto_start doit être à off',
        'ini.safe_mode'         =>'php.ini : le safe_mode n\'est pas recommandé pour jelix.',
        'ini.register_globals'  =>'php.ini : il faut désactiver register_globals, pour des raisons de sécurité et parce que Jelix n\'en a pas besoin.',
        'ini.asp_tags'          =>'php.ini :  il est conseillé de désactiver asp_tags. Jelix n\'en a pas besoin.',
        'ini.short_open_tag'    =>'php.ini :  il est conseillé de désactiver short_open_tag. Jelix n\'en a pas besoin.',
        'ini.ok'                =>'Les paramètres de php sont ok',

        'module.unknown'        =>'Module inconnu',
        'module.circular.dependency'=>"Dépendance circulaire ! le composant %s ne peut être installé",
        'module.needed'         =>'Pour installer le module %s, ces modules doivent être présent : %s',
        'module.bad.jelix.version'=>'Le module %s necessite une autre version de jelix (%s - %s)',
        'module.bad.dependency.version'=>'Le module %s necessite une autre version du module %s (%s - %s)',
        'module.installer.class.not.found'=>'La classe d\'installation %s pour le module %s n\'existe pas',
        'module.upgrader.class.not.found'=>'La classe de mise à jour %s pour le module %s n\'existe pas',
        
        'install.entrypoint.start'  =>'Installation pour le point d\'entrée %s',
        'install.entrypoint.end'    =>'Tout les modules sont installés ou mise à jour pour le point d\'entrée %s',
        'install.entrypoint.bad.end'=>'Installation interrompue pour cause d\'erreurs pour le point d\'entrée %s',
        
        'install.dependencies.ok'   =>'Toutes les dépendances des modules sont valides',
        'install.bad.dependencies'  =>'Il y a des erreurs dans les dépendances. Installation annulée.',
        'install.invalid.xml.file'  =>'Le fichier identité %s est invalide ou inexistant',
        
        'install.module.already.installed'  =>'Le module %s déjà installé',
        'install.module.installed'          =>'Le module %s est installé',
        'install.module.error'              =>'Une erreur est survenue durant l\'installation du module %s: %s',
        'install.module.check.dependency'   =>'Vérifie les dépendances du module %s',
        'install.module.upgraded'           =>'Le module %s est mis à jour à la version %s',

