
<table>
   <tr><th>id</th><th>group</th><th>value</th></tr>
  {foreach $config as $conf}
  <tr><td>{$conf->id}</td><td>{$conf->grp}</td><td>{$conf->value}</td></tr>
  {/foreach}
</table>
<p>This is a sample zone generated by {@jelix~jelix.framework.name@}</p>

<p>one conf id={$oneconf->id} grp={$oneconf->grp} val={$oneconf->value}</p>

<h2>utilisateurs</h2>

<table>
   <tr><th>login</th><th>group</th><th>email</th></tr>
  {foreach $users as $u}
  <tr><td>{$u->login}</td><td>{$u->groupname}</td><td>{$u->email}</td></tr>
  {/foreach}
</table>
