#!/usr/bin/env bash
basedir=$(dirname "$0")
rootdir=$(realpath $basedir/../)
COMMAND="$1"
shift

if [ -f $basedir/.env ]; then
  source $basedir/.env
fi

if [ "$JLX_BRANCH" == "" ]; then
    JLX_BRANCH=$(git rev-parse --abbrev-ref HEAD)
    JLX_BRANCH="${JLX_BRANCH//.}"
    export JLX_BRANCH="${JLX_BRANCH//-}"
fi

if [ "$COMMAND" == "" ]; then
    echo "Error: command is missing"
    echo "Possible commands: "
    echo "- Into php: reset, rights, clean-temp, install, composer-install,"
    echo "  composer-update, unit-tests"
    echo "- To manage the ldap server: ldap-reset, ldap-users"
    echo "- To enter into the php container: shell, shell-root"
    echo "- to enter into a interactive database shell: pgsql, mysql or redis"
    echo "- other: mysql-root"
    exit 1;
fi

case $COMMAND in
    clean-temp)
        docker exec -t -i jelix_${JLX_BRANCH}_test_php appctl.sh clean_tmp;;
    reset)
        docker exec -t -i jelix_${JLX_BRANCH}_test_php appctl.sh reset;;
    install)
        docker exec -t -i jelix_${JLX_BRANCH}_test_php appctl.sh install;;
    rights)
        docker exec -t -i jelix_${JLX_BRANCH}_test_php appctl.sh rights;;
    composer-install)
        docker exec -t -i jelix_${JLX_BRANCH}_test_php appctl.sh composer_install;;
    composer-update)
        docker exec -t -i jelix_${JLX_BRANCH}_test_php appctl.sh composer_update;;
    unit-tests)
        docker exec -t -i jelix_${JLX_BRANCH}_test_php appctl.sh unit-tests $@;;
    shell)
       docker exec -it --user userphp jelix_${JLX_BRANCH}_test_php  /bin/bash -l;;
    shell-root)
       docker exec -it jelix_${JLX_BRANCH}_test_php  /bin/bash  -l;;
    ldap-reset)
      docker exec -it jelix_${JLX_BRANCH}_test_ldap /bin/ctl.sh reset
      ;;
    ldap-users)
       docker exec -it jelix_${JLX_BRANCH}_test_ldap /bin/ctl.sh showusers
       ;;
    pgsql)
       docker exec -it --user postgres -e PGPASSWORD="jelix" jelix_${JLX_BRANCH}_test_pgsql psql --username=test_user testapp
       ;;
    redis)
      docker exec -it jelix_${JLX_BRANCH}_test_redis redis-cli
      ;;
    mysql)
      docker exec -it jelix_${JLX_BRANCH}_test_mysql mysql -u test_user -pjelix testapp
      ;;
    mysql-root)
      docker exec -it jelix_${JLX_BRANCH}_test_mysql /bin/bash  -l
      ;;
    *)
        echo "wrong command"
        exit 2
        ;;
esac

