#!/usr/bin/env bash

set -e

export JELIX_USER_ID=${JELIX_USER_ID:-$(id -u)}
export JELIX_GROUP_ID=${JELIX_GROUP_ID:-$(id -g)}

CMD=$1

if [ "$CMD" == "" ]; then
    CMD="up -d"
fi

if [ "$JLXBRANCH" == "" ]; then
  export JLXBRANCH=$(git rev-parse --abbrev-ref HEAD)
fi

if [ "$TESTAPP_WEB_PORT" == "" ]; then
  export TESTAPP_WEB_PORT=8817
fi

if [ "$PHP_VERSION" == "" ]; then
  export PHP_VERSION=7.4
fi

if [ "$CMD" == "build" ]; then
  if [ ! -f docker-conf/certs/ldap.jelix.crt ]; then
    (
    cd docker-conf;
    ./setup.sh
    )
  fi
fi


docker-compose -p jelix-${JLXBRANCH}-tests $CMD
