#!/usr/bin/env bash

set -e

export JELIX_USER_ID=${JELIX_USER_ID:-$(id -u)}
export JELIX_GROUP_ID=${JELIX_GROUP_ID:-$(id -g)}

CMD=$1

if [ "$JLXBRANCH" == "" ]; then
  export JLXBRANCH=$(git rev-parse --abbrev-ref HEAD)
fi

if [ "$TESTAPP_WEB_PORT" == "" ]; then
  export TESTAPP_WEB_PORT=8820
fi

if [ "$PHP_VERSION" == "" ]; then
  export PHP_VERSION=8.2
fi

if [ "$CMD" == "build" ]; then
  if [ ! -f docker-conf/certs/ldap.jelix.crt ]; then
    (
    cd docker-conf;
    ./setup.sh
    )
  fi

  # be sure to have the latest image
  docker pull 3liz/liz-php-fpm:$PHP_VERSION
fi

if [ "$CMD" == "reset" ]; then
    # Stop/Remove containers
    docker compose -p jelix-${JLXBRANCH}-tests rm -sf || true
    # Clean db volumes
    docker volume rm "jelix_${JLXBRANCH}_pg_data" || true
    docker volume rm "jelix_${JLXBRANCH}_mysql_data" || true
    exit 0
elif [ -z "$CMD" ]; then
    CMD="up"
else
    shift
fi


docker compose -p jelix-${JLXBRANCH}-tests $CMD
