<h1>Hello world</h1>
<p>This is a simple page generated by Jelix. </p>
<p style="color:red;">This template should <strong>NOT</strong> be displayed as
a copy is available into the module theme directory.</p>

<p><a href="{jurl 'main:index'}">Back to main page</a></p>
