<h1>Hello {$person|upper} !</h1>
<p>Ceci est une simple page générée par {@jelix~jelix.framework.$value@}</p>
<p>This is a sample html page generated by {@jelix~jelix.framework.$value@}</p>
<p>Dîtes <a href="{jurl 'main_hello',array('person'=>'Bob')}">bonjour à Bob</a>.</p>


<p><a href="{jurl 'main_index'}">Retour au sommaire</a></p>

<!--
<p>Link to actions:</p>
<ul>
<li> "testapp~main_index@classic" : {jurl "testapp~main_index@classic"}</li>
<li> "main_index@classic": {jurl "main_index@classic"}</li>
<li> "main_index" : {jurl "main_index"}</li>
<li> "testapp~main_" : {jurl "testapp~main_"}</li>
<li> "testapp~#" : {jurl "testapp~#"}</li>
<li> "#~#" : {jurl "#~#"}</li>
<li> "@" : {jurl "@"}</li>
</ul>
-->