<h1>Hello {$person|upper} !</h1>
<p>This is a sample html page generated by {@jelix~jelix.framework.$value@}</p>
<p>Say <a href="{jurl 'main:hello',array('person'=>'Bob')}">Hello to Bob</a>.</p>


<p><a href="{jfullurl 'main:index'}">Back to main page</a></p>

<!--
<p>Link to actions:</p>
<ul>
<li> "testapp~main:index@classic" : {jurl "testapp~main:index@classic"}</li>
<li> "main:index@classic": {jurl "main:index@classic"}</li>
<li> "main:index" : {jurl "main:index"}</li>
<li> "testapp~main:" : {jurl "testapp~main:"}</li>
<li> "testapp~#" : {jurl "testapp~#"}</li>
<li> "#~#" : {jurl "#~#"}</li>
</ul>
-->
