<h1>Sample form</h1>
<p>Here is a form generated and managed entirely by jforms</p>
{if $builder == 'html'}{assign $newbuilder="htmllight"}{else}{assign $newbuilder="html"}{/if}
<p>The form content is generated by the builder "{$builder}". If you want to see
the look of the form with the builder "{$newbuilder}", 
<a href="{jurl 'testapp~sampleform:show', array('full'=>1, 'builder'=>$newbuilder)}">click here</a>.

{formfull $form,'sampleform:save', array(), $builder}
