
<table>
   <tr><th>key</th><th>value</th></tr>
  {foreach $config as $conf}
  <tr><td>{$conf->ckey}</td><td>{$conf->cvalue}</td></tr>
  {/foreach}
</table>
<p>Count = {$nombre}</p>
<p>Count of value that contains "value" = {$nombrevalue}</p>
<p>This is a sample zone generated by {@jelix~jelix.framework.name@}</p>

<p>one conf key={$oneconf->ckey} value={$oneconf->cvalue}</p>
<p>Link to actions:</p>
<ul>
<li> "testapp~default@classic" : {jurl "testapp~default@classic"}</li>
<li> "default@classic": {jurl "default@classic"}</li>
<li> "default" : {jurl "default"}</li>
<li> "testapp~default" : {jurl "testapp~default"}</li>
<li> "testapp~#" : {jurl "testapp~#"}</li>
<li> "#~#" : {jurl "#~#"}</li>
<li> "@" : {jurl "@"}</li>
</ul>
