;<?php die('');?>

[entrypoint:index.php]
config="index/config.ini.php"
type=classic
default=on
[entrypoint:rest.php]
config="rest/config.ini.php"
type=classic
[entrypoint:testnews.php]
config="index/config.ini.php"
type=classic
[entrypoint:foo/bar.php]
config="index/config.ini.php"
type=classic
[entrypoint:invisible.php]
config="index/config.ini.php"
type=classic
[entrypoint:noep.php]
config="index/config.ini.php"
type=classic
[entrypoint:handlermodule.php]
config="index/config.ini.php"
type=classic
[entrypoint:news.php]
config="index/config.ini.php"
type=classic
[entrypoint:soap.php]
config="soap/config.ini.php"
type=soap
[entrypoint:jsonrpc.php]
config="jsonrpc/config.ini.php"
type=jsonrpc
[entrypoint:xmlrpc.php]
config="xmlrpc/config.ini.php"
type=xmlrpc
[entrypoint:cmdline.php]
config="cmdline/config.ini.php"
type=cmdline

[entrypoint:newep.php]
config="newep/config.ini.php"
type=classic
