;<?php die('');?>

[entrypoint:index.php]
config="index/config.ini.php"
type=classic
default=on
[entrypoint:rest.php]
config="rest/config.ini.php"
type=classic
[entrypoint:testnews.php]
config="index/config.ini.php"
type=classic
[entrypoint:foo/bar.php]
config="index/config.ini.php"
type=classic
[entrypoint:invisible.php]
config="index/config.ini.php"
type=classic
[entrypoint:noep.php]
config="index/config.ini.php"
type=classic
[entrypoint:handlermodule.php]
config="index/config.ini.php"
type=classic
[entrypoint:news.php]
config="index/config.ini.php"
type=classic
[entrypoint:soap.php]
config="soap/config.ini.php"
type=soap
[entrypoint:jsonrpc.php]
config="jsonrpc/config.ini.php"
type=jsonrpc
[entrypoint:xmlrpc.php]
config="xmlrpc/config.ini.php"
type=xmlrpc
[entrypoint:newep.php]
config="newep/config.ini.php"
type=classic

[module:jelix_tests]
enabled=on
[module:testapp]
enabled=on
[module:testurls]
enabled=on
[module:jsoap]
enabled=on
[module:jacl2]
enabled=on
[module:jacl2db]
enabled=on
installparam[defaultgroups]=on
installparam[defaultuser]=on
[module:jauthdb]
enabled=on
[module:jauth]
enabled=on
[module:jminify]
enabled=on
[module:jfeeds]
enabled=on
[module:jsitemap]
enabled=on
[module:news]
enabled=on
[module:articles]
enabled=on
[module:jelix]
enabled=on
installparam[wwwfiles]=vhost
