<?php
/**
* @package     testapp
* @subpackage  jelix_tests module
* @author      Laurent Jouanneau
* @contributor
* @copyright   2019-2025 Laurent Jouanneau
* @link        http://www.jelix.org
* @licence     GNU Lesser General Public Licence see LICENCE file or http://www.gnu.org/licenses/lgpl.html
*/

use Jelix\Core\Profiles;
use Jelix\Dao\DbMapper;
use Jelix\DaoUtils\DaoContext;

require_once(__DIR__.'/jdao_main_api.lib.php');
/**
 * same tests as jdao_main_api_pdo, but with a pgsql connection
 */
class jdao_main_api_pgsqlTest extends jdao_main_api_base {
    static protected $trueValue = 't';
    static protected $falseValue = 'f';

    function setUp() : void  {
        parent::setUp();
        $this->schemaClass = '\Jelix\Database\Schema\Postgresql\Schema';

        try {
            Profiles::get('jdb', 'testapp_pgsql', true);
        }
        catch(Exception $e) {
            $this->markTestSkipped(get_class($this).' cannot be run: undefined testapp_pgsql profile');
            return;
        }
        $this->dbProfile ='testapp_pgsql';
    }

    function testInstanciation() {
        $dao = jDao::create ('products', $this->dbProfile);
        $this->assertInstanceOf('\Jelix\BuiltComponents\Daos\Jelix_tests\ProductsPgsqlFactory', $dao);

        $dao = jDao::get ('products', $this->dbProfile);
        $this->assertInstanceOf('\Jelix\BuiltComponents\Daos\Jelix_tests\ProductsPgsqlFactory', $dao);

        $daorec = jDao::createRecord ('products', $this->dbProfile);
        $this->assertInstanceOf('\Jelix\BuiltComponents\Daos\Jelix_tests\ProductsPgsqlRecord', $daorec);

        $daorec = $dao->createRecord();
        $this->assertInstanceOf('\Jelix\BuiltComponents\Daos\Jelix_tests\ProductsPgsqlRecord', $daorec);
    }

    // create a table with an identity on id, and try to transform it to serial
    function testDbMapperModifiedIdentityToSerial()
    {
        $db = jDb::getConnection($this->dbProfile);
        $db->exec('DROP TABLE IF EXISTS article3serial');
        $db->exec('CREATE TABLE "article3serial" ("id" integer generated by default as identity, "category_id" integer NOT NULL, "title" varchar(200) NOT NULL, "content" text NOT NULL)');

        $context = new DaoContext($db->getSQLType());
        $mapper = new DbMapper($context, $db);
        $mapper->createTableFromDao($context->resolveDaoPath('article3serial'));

        $db = jDb::getConnection($this->dbProfile);
        // we want a new instance of the schema object
        $schema = new $this->schemaClass($db);


        $table = $schema->getTable('article3serial');
        $this->assertNotNull($table);

        $columns = $table->getColumns();
        $this->assertEquals(['id', 'category_id', 'title', 'content'], array_keys($columns));
        $this->assertEquals(255, $columns['title']->length);
        $this->assertEquals('integer', $columns['id']->type);
        $db->exec('DROP TABLE IF EXISTS article3serial');
    }

    function testDbMapperModifiedIntegerToSerial()
    {
        $db = jDb::getConnection($this->dbProfile);
        $db->exec('DROP TABLE IF EXISTS article3serial');
        $db->exec('CREATE TABLE "article3serial" ("id" integer, "category_id" integer NOT NULL, "title" varchar(200) NOT NULL, "content" text NOT NULL)');

        $context = new DaoContext($db->getSQLType());
        $mapper = new DbMapper($context, $db);
        $mapper->createTableFromDao($context->resolveDaoPath('article3serial'));


        $db = jDb::getConnection($this->dbProfile);
        // we want a new instance of the schema object
        $schema = new $this->schemaClass($db);

        $table = $schema->getTable('article3serial');
        $this->assertNotNull($table);

        $columns = $table->getColumns();
        $this->assertEquals(['id', 'category_id', 'title', 'content'], array_keys($columns));
        $this->assertEquals(255, $columns['title']->length);
        $this->assertEquals('integer', $columns['id']->type);
        $db->exec('DROP TABLE IF EXISTS article3serial');
    }

}
